import { useContext, useEffect, useState } from "react";
import Head from "next/head";
import { createTestAcc } from "../../algorand";
import styles from "../styles/Home.module.css";
import Context from "../context/Context";
import { ActionType } from "../context/reducer";

export default function Home() {
  const context = useContext(Context);
  const [address, setAddress] = useState("");
  const [status, setStatus] = useState("");
  const [claim, setClaim] = useState("");

  useEffect(() => {
    if (window) {
      const data = localStorage.getItem("insurer-acc");

      if (!data) {
        const user = createTestAcc();
        setAddress(user!.acc.addr);
        context.dispatch?.({
          type: ActionType.SET_INSURERACC,
          payload: {
            insurerAcc: {
              acc: user!.acc,
              mnemonic: user!.mnemonic,
            },
          },
        });
      } else {
        const key = JSON.parse(data);
        setAddress(key.acc.addr);
      }
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const claiming = async () => {
    setStatus(`Claiming ${claim}...`);
    const client = createTestAcc();
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h2> Hæ hæ , smá algorand demo</h2>
        <strong>
          <p className={styles.walletInfo}>
            Insurer wallet: <i>{address}</i>
          </p>
        </strong>
        <select
          className={styles.select}
          onChange={(e) => setClaim(e.target.value)}
        >
          <option value="sjúkrakostnaðartrygging">
            Sjúkrakostnaðartrygging
          </option>
          <option value="umönnunartrygging">Umönnunartrygging</option>
        </select>

        <button className={styles.button} onClick={claiming}>
          Claim
        </button>

        <p>{status}</p>
      </main>
    </div>
  );
}
